name: build-admin
on:
  push:
    branches: [ main, develop ]
jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - name: Login GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set tags
        id: meta
        run: |
          if [ "${{ github.ref_name }}" = "main" ]; then
            echo "TAGS=main" >> $GITHUB_OUTPUT
          else
            echo "TAGS=develop" >> $GITHUB_OUTPUT
          fi
      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ghcr.io/ifedayoagboola/bitsgiga-admin:${{ steps.meta.outputs.TAGS }}
